pipeline {
    agent any

    environment {
        PHP_PATH = 'C:\\xampp8.2\\php\\php.exe'  
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Check Environment') {
            steps {
                bat """
                    set PATH=%PHP_PATH%;%PATH%
                    where php
                    php -v
                    where composer
                    composer --version
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                bat """
                    set PATH=%PHP_PATH%;%PATH%
                    composer install
                """
            }
        }

        stage('Run PHPUnit Tests') {
            steps {
                bat """
                    set PATH=%PHP_PATH%;%PATH%
                    vendor\\bin\\phpunit tests
                """
            }
        }
    }

    post {
        success {
            echo 'Build Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
        always {
            cleanWs()
        }
    }
}